// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package postgres

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type IndexGeneration struct {
	Collection string
	Name       string
	BuiltAt    pgtype.Timestamptz
	PromotedAt pgtype.Timestamptz
	Documents  int64
}

type SyncCheckpoint struct {
	Collection     string
	UpdatedThrough pgtype.Timestamptz
	LastID         string
	SavedAt        pgtype.Timestamptz
}
