// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package postgres

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const loadCheckpoint = `-- name: LoadCheckpoint :one
SELECT updated_through, last_id, saved_at FROM sync_checkpoint WHERE collection = $1
`

type LoadCheckpointRow struct {
	UpdatedThrough pgtype.Timestamptz
	LastID         string
	SavedAt        pgtype.Timestamptz
}

func (q *Queries) LoadCheckpoint(ctx context.Context, collection string) (LoadCheckpointRow, error) {
	row := q.db.QueryRow(ctx, loadCheckpoint, collection)
	var i LoadCheckpointRow
	err := row.Scan(&i.UpdatedThrough, &i.LastID, &i.SavedAt)
	return i, err
}

const markGenerationPromoted = `-- name: MarkGenerationPromoted :exec
UPDATE index_generation SET promoted_at = now()
WHERE collection = $1 AND name = $2
`

type MarkGenerationPromotedParams struct {
	Collection string
	Name       string
}

func (q *Queries) MarkGenerationPromoted(ctx context.Context, arg MarkGenerationPromotedParams) error {
	_, err := q.db.Exec(ctx, markGenerationPromoted, arg.Collection, arg.Name)
	return err
}

const recordGeneration = `-- name: RecordGeneration :exec
INSERT INTO index_generation (collection, name, documents)
VALUES ($1, $2, $3)
ON CONFLICT (collection, name) DO UPDATE SET documents = EXCLUDED.documents
`

type RecordGenerationParams struct {
	Collection string
	Name       string
	Documents  int64
}

func (q *Queries) RecordGeneration(ctx context.Context, arg RecordGenerationParams) error {
	_, err := q.db.Exec(ctx, recordGeneration, arg.Collection, arg.Name, arg.Documents)
	return err
}

const saveCheckpoint = `-- name: SaveCheckpoint :exec
INSERT INTO sync_checkpoint (collection, updated_through, last_id, saved_at)
VALUES ($1, $2, $3, now())
ON CONFLICT (collection) DO UPDATE
   SET updated_through = EXCLUDED.updated_through,
       last_id         = EXCLUDED.last_id,
       saved_at        = EXCLUDED.saved_at
`

type SaveCheckpointParams struct {
	Collection     string
	UpdatedThrough pgtype.Timestamptz
	LastID         string
}

func (q *Queries) SaveCheckpoint(ctx context.Context, arg SaveCheckpointParams) error {
	_, err := q.db.Exec(ctx, saveCheckpoint, arg.Collection, arg.UpdatedThrough, arg.LastID)
	return err
}
